csplib/csplib

Problems/prob001/references/references.bib
Hi, 
I updated the references on prob001 by the ones I have in my local bibtex file. Add them to the repository if you like. 
Cheers, 
Valentin
=> References for prob001:Car Sequencing updated.

Problems/prob003/specification.md
=> Fix formatting in quasigroup existence

internal/scripts/framework/bibtex.py, internal/templates/bib_format.html
Show the publisher for books in the references section. Only for books at the moment
=> Show the publisher for books in the references section, fixes #68

Problems/prob065/references/references.bib, internal/scripts/framework/bibtex.py, internal/templates/bib_format.html
Add 'pages' to the bibtex output
=> Use 'pages' information

Problems/prob001/data/roadef_instances.inline.md, Problems/prob001/models/sat_encoder.inline.md
I added a link to Data and Model for prob001.
=> Link to SAT encoder and ROADEF instances added

internal/templates/updates.html
Shown recent problems first in updates, and note these updates are for new problems
=> Shown recent problems first in updates

Problems/prob019/specification.md, Problems/prob024/specification.md, Problems/prob036/specification.md
=> Minor Latex fixes

Problems/prob007/specification.md
Not 100% sure if I have done the crossref linking to another problem right.
=> Adding xref from All Interval to Graceful graphs

Problems/prob053/specification.md
Changed to {prob007} syntax so hopefully mergeable
=> Turingfan patch 3

Problems/prob040/models/DistributionWagnerWhitin.essence
Sorry I am submitting these one by one. This should be the last one...
=> another missing toInt in an Essence file

Problems/prob021/models/Crossfigures.essence, Problems/prob021/models/Crossfigures.essence.metadata, Problems/prob021/references/notes.inline.md, Problems/prob021/references/references.bib
Updating the Essence model for Crossfigures, and adding a link to archive.org because the original website (thinks.com) seems to be inaccessible.
=> Cross figures

Problems/prob030/references/references.bib
Data derived from Google Scholar
=> Improved references to add URLs

Problems/prob054/models/nqueens.essence.metadata
=> Deleted a unneeded file

Readme.md
@ChrisJefferson and @Bilalh, how do you like these badges in the README?
Check the following to see how they'd look like: https://github.com/ozgurakgun/csplib/blob/badges/Readme.md
=> adding badges to the README for the license (CC BY 4.0) and travis build status

internal/scripts/support/pyvenvex.py
=> Updated the pip install script to fix ubuntu 16.04 LTS

internal/scripts/framework/util.py
@turingfan had this problem when he was adding a new problem.
=> Add tgz to the list of known archive formats

Problems/prob009/models/PerfectSquarePlacement.essence, Problems/prob013/models/ProgressivePartyProblem.essence, Problems/prob017/models/RamseyNumbers.essence, Problems/prob025/models/Lam.essence, Problems/prob026/models/SportsTournamentScheduling.essence, Problems/prob028/models/BIBD.essence, Problems/prob031/models/RackConfiguration.essence, Problems/prob033/models/WordDesign.essence, Problems/prob038/models/SteelMillSlabDesignProblem.essence, Problems/prob054/models/nqueens.essence, Problems/prob116/models/Vellino.essence
Updated models based on the results from running the `model-strengthening` feature of Conjure on them. Only those that make a positive difference have been applied.
=> Model strengthening results

Problems/prob079/specification.md
Change category to "Games and puzzles" from "Games and Puzzles"
=> case change

Problems/prob034/specification.md
The first value in cost matrix was missing.
Added value from [here](https://github.com/csplib/csplib/blob/master/Problems/prob034/models/sicstus_csplib034.pl#L138)
=> Adding missing cost value - supplyCost[0,0] = 20

Problems/prob012/specification.md, Problems/prob053/models/k4p2-graceful-graph-ortools.cc, Problems/prob053/models/k4p2-graceful-graph-ortools.cc.metadata, Problems/prob054/models/nqueens-ortools.cc, Problems/prob054/models/nqueens-ortools.cc.metadata
Added new models for n-Queens and k4p2 graceful graphs in OR-tools C++
=> New models

Problems/prob051/data/synthetic.zip.metadata, Problems/prob051/data/synthetic_generator.py, Problems/prob051/data/synthetic_generator.py.metadata, Problems/prob051/references/references.bib
Add new instances created for the article "Improved filtering for the bin-packing with cardinality constraint", along with the python script used to generate those.
=> Add new instances for prob051 - Chemical Tanker

.travis.yml, Readme.md
Make a simpler travis script, which just builds the website
=> Fix travis

Problems/prob028/models/BIBD.essence
As discussed in Slack and email.
=> remove incorrect conditions from BIBD spec

.travis.yml, internal/scripts/framework/util.py, internal/scripts/support/packages.txt
=> Fixing travis

BrokenLinkChecker-report-2019-12-13.html, Languages/ECLiPSe/specification.md, Problems/prob003/references/references.bib, Problems/prob006/references/references.bib, Problems/prob007/results/results.inline.md, Problems/prob018/results/notes.inline.md, Problems/prob019/references/notes.inline.md, Problems/prob019/results/notes.inline.md, Problems/prob023/models/models.inline.md, Problems/prob023/references/references.bib, Problems/prob023/results/results.inline.md, Problems/prob024/references/notes.inline.md, Problems/prob032/references/references.bib, Problems/prob032/specification.md, Problems/prob033/results/results.inline.md, Problems/prob037/models/models.inline.md, Problems/prob037/references/references.bib, Problems/prob064/specification.md, Problems/prob066/models/notes.inline.md, Problems/prob069/references/references.bib, Problems/prob076/specification.md, Problems/prob079/references/references.bib, Problems/prob080/references/references.bib
I have attempted to fix a bunch of broken links.  There are still many remaining, but I didn't know how much time I would have soon to do the rest, so thought I'd offer these for now.  I have tried, where possible, to research a newer working link. Otherwise I've tried to find the archive.org historical snapshot.
There is a file `BrokenLinkChecker-report-2019-12-13.html` which was the basis of my hunting - it's obviously not needed for the site, it's just there for reference.
=> Fixed some broken links, unfortunately not all (yet)

Problems/prob008/data/easy-minizinc.dzn, Problems/prob008/data/easy-minizinc.dzn.metadata, Problems/prob008/data/harder-minizinc.dzn, Problems/prob008/data/harder-minizinc.dzn.metadata, Problems/prob008/models/vessel-loading.mzn, Problems/prob008/models/vessel-loading.mzn.metadata
I made a model for the Vessel Loading problem (prob008) in MiniZinc with two data files corresponding to the two essence parameter files.
=> Added MiniZinc model for prob008: Vessel Loading

internal/templates/index.html
was it 1999 or is my memory failing me?
=> not really 17 years any more

Problems/prob088/references/references.bib, Problems/prob088/specification.md
Now that the Plotting paper is published, I added the proper full citation.
=> Final version of Plotting
